export const recipes = [
    'Place the warm water in the large bowl of a heavy duty stand mixer. Sprinkle the yeast over the warm water and let it sit for 5 minutes until the yeast is dissolved.',
    'Add the flour, salt, sugar, and olive oil, and using the mixing paddle attachment, mix on low speed for a minute. Then replace the mixing paddle with the dough hook attachment.',
    'Spread a thin layer of olive oil over the inside of a large bowl. Place the pizza dough in the bowl and turn it around so that it gets coated with the oil.',
    'lace a pizza stone on a rack in the lower third of your oven. Preheat the oven to 475°F (245°C) for at least 30 minutes, preferably an hour.',
    'Remove the plastic cover from the dough. Dust your hands with flour and push the dough down so it deflates a bit. Divide the dough in half.',
    'Prepare your desired toppings. Note that you are not going to want to load up each pizza with a lot of toppings as the crust will end up not crisp that way.',
    'Working one ball of dough at a time, take one ball of dough and flatten it with your hands on a lightly floured work surface.',
    'Use your fingertips to press down and make dents along the surface of the dough to prevent bubbling.',
    'Lightly sprinkle your pizza peel (or flat baking sheet) with cornmeal. ',
    'Spoon on the tomato sauce, sprinkle with cheese, and place your desired toppings on the pizza.',
    'Sprinkle some cornmeal on the baking stone in the oven (watch your hands, the oven is hot!).',
    'Bake pizza in the 475°F (245°C) oven, one at a time, until the crust is browned and the cheese is golden, about 10-15 minutes.',
    'Place the warm water in the large bowl of a heavy duty stand mixer. Sprinkle the yeast over the warm water and let it sit for 5 minutes until the yeast is dissolved.',
    'Add the flour, salt, sugar, and olive oil, and using the mixing paddle attachment, mix on low speed for a minute. Then replace the mixing paddle with the dough hook attachment.',
    'Spread a thin layer of olive oil over the inside of a large bowl. Place the pizza dough in the bowl and turn it around so that it gets coated with the oil.',
    'lace a pizza stone on a rack in the lower third of your oven. Preheat the oven to 475°F (245°C) for at least 30 minutes, preferably an hour.',
    'Remove the plastic cover from the dough. Dust your hands with flour and push the dough down so it deflates a bit. Divide the dough in half.',
    'Prepare your desired toppings. Note that you are not going to want to load up each pizza with a lot of toppings as the crust will end up not crisp that way.',
    'Working one ball of dough at a time, take one ball of dough and flatten it with your hands on a lightly floured work surface.',
    'Use your fingertips to press down and make dents along the surface of the dough to prevent bubbling.',
    'Lightly sprinkle your pizza peel (or flat baking sheet) with cornmeal. ',
    'Spoon on the tomato sauce, sprinkle with cheese, and place your desired toppings on the pizza.',
    'Sprinkle some cornmeal on the baking stone in the oven (watch your hands, the oven is hot!).',
    'Bake pizza in the 475°F (245°C) oven, one at a time, until the crust is browned and the cheese is golden, about 10-15 minutes.'
]

export const ingredient =[
    '1 1/2 cups (355 ml) warm water (105°F-115°F)',
    '1 package (2 1/4 teaspoons) of active dry yeast',
    '3 3/4 cups (490 g) bread flour',
    '2 tablespoons extra virgin olive oil (omit if cooking pizza in a wood-fired pizza oven)',
    '2 teaspoons salt',
    '1 teaspoon sugar',
    'Extra virgin olive oil',
    'Cornmeal (to help slide the pizza onto the pizza stone)',
    'Tomato sauce (smooth, or puréed)',
    'Firm mozzarella cheese, grated',
    'Fresh soft mozzarella cheese, separated into small clumps',
    'Fontina cheese, grated',
    'Parmesan cheese, grated',
    'Feta cheese, crumbled',
    'Mushrooms, very thinly sliced if raw, otherwise first sautéed',
    'Bell peppers, stems and seeds removed, very thinly sliced',
    'Italian pepperoncini, thinly sliced',
    'Italian sausage, cooked ahead and crumbled',
    'Chopped fresh basil',
    'Baby arugula, tossed in a little olive oil, added as pizza comes out of the oven',
    'Pesto',
    'Pepperoni, thinly sliced',
    'Onions, thinly sliced raw or caramelized',
    'Ham, thinly sliced'
]